# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7806bb235a41d6b9e2b13e467ded994c59c0961419b2f9f8066bed2c735d18eb2a3dfd170f1e0fd5cb3f21aea55a67727adba22ca3f3a1029369d48f70f6b5

test:
  secret_key_base: de2e91412853e186d087c96a65a8133cbcf961c7c2881b70d3469bdd67766f083764875a7bd621a54d8dbb98ff5990e2599322cf8dbad2642df7efdf354e69e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
